services:
    app.validator.old_password:
        class: AppBundle\Validator\Constraints\OldPasswordValidator
        arguments:
            - "@security.password_encoder"
        tags:
            - { name: validator.constraint_validator, alias: old_password }

    app.validator.ownership_status:
        class: AppBundle\Validator\Constraints\OwnershipStatusValidator
        arguments:
            - "@doctrine.orm.doctrine_entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: ownership_status }

    app.validator.city_exist:
        class: AppBundle\Validator\Constraints\CityExistValidator
        arguments:
            - "@doctrine.orm.doctrine_entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: city_exist }

    app.validator.street_exist:
        class: AppBundle\Validator\Constraints\StreetExistValidator
        arguments:
            - "@doctrine.orm.doctrine_entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: street_exist }

    app.validator.house_exist:
        class: AppBundle\Validator\Constraints\HouseExistValidator
        arguments:
            - "@doctrine.orm.doctrine_entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: house_exist }

    app.validator.flat_exist:
        class: AppBundle\Validator\Constraints\FlatExistValidator
        arguments:
            - "@doctrine.orm.doctrine_entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: flat_exist }

    app.validator.mkd_exist:
        class: AppBundle\Validator\Constraints\MKDExistValidator
        arguments:
            - "@doctrine.orm.doctrine_entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: mkd_exist }

    app.validator.share_size:
        class: AppBundle\Validator\Constraints\ShareSizeValidator
        tags:
            - { name: validator.constraint_validator, alias: share_size }
